services:
    nginx:
        build: ./requirements/nginx/
        ports:
            - "443:443"
        volumes:
            - website:/www
volumes:
    website:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/data/website
