services:
    nginx:
        build: ./requirements/nginx/
        image: nginx
        ports:
            - "443:443"
        volumes:
            - website:/www
        restart: always
    wordpress:
        build:
            context: ./requirements/wordpress/
            args:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        image: wordpress
        volumes:
            - website:/www
        restart: always
    mariadb:
        build: ./requirements/mariadb/
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: always
volumes:
    website:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/data/website
