version: '3.8'
services:
    nginx:
        build: ./requirements/nginx/
        image: nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        volumes:
            - website:/www
        networks:
            - docker-network
        restart: always
    wordpress:
        build:
            context: ./requirements/wordpress/
            args:
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        image: wordpress
        depends_on:
            - mariadb
        volumes:
            - website:/www
        networks:
            - docker-network
        restart: always
    mariadb:
        build: ./requirements/mariadb/
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - database:/var/lib/mysql
        networks:
            - docker-network
        restart: always
volumes:
    website:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/data/website
    database:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/data/database
networks:
    docker-network:
        driver: bridge
