services:
    nginx:
        build: ./requirements/nginx/
        image: nginx
        ports:
            - "443:443"
        volumes:
            - website:/www
        restart: always
    wordpress:
        build: ./requirements/wordpress/
        image: wordpress
        volumes:
            - website:/www
        restart: always
volumes:
    website:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/data/website
